powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/encryption/BasicEciesEncryptorTest.java

Note that we may still refactor ECIES a bit for Crypto 3.0 (e.g. change deriving of `sharedInfo1` which is now present in the test, consider using the `ECIESEnvelopeKey` like in the mobile SDK, etc.). So at least we can easily test such changes because of `v2` and `v3` tests.

Fix #195: Crypto 3.0: New test vectors for ECIES

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesFactory.java

Minor update of factory to allow using the factory for activation layer 2 which requires internal `sharedInfo1` in application scope.

Fix #209: Crypto 3.0: Update EciesFactory for activation layer 2 usage

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/keyfactory/PowerAuthClientKeyFactory.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/vault/PowerAuthClientVault.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/enums/PowerAuthDerivedKey.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/generator/KeyGenerator.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/keyfactory/PowerAuthServerKeyFactory.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/vault/PowerAuthServerVault.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/vault/VaultTest.java

Changes in this PR:
- Fix #211: Crypto 3.0: Switch to byte array for counter in vault unlock
- Key index used during key derivation uses byte array instead of long so that only one deriveSecretKey() method is used for both derivation using counter and using key

Fix #211: Crypto 3.0: Switch to byte array for counter in vault unlock

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/activation/PowerAuthClientActivation.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/signature/PowerAuthClientSignature.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/generator/IdentifierGenerator.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/SignatureUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/activation/PowerAuthServerActivation.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/signature/PowerAuthServerSignature.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/activation/PowerAuthActivationTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/GenerateVectorDataTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/signature/PowerAuthSignatureTest.java

Deprecated methods can be removed, there are no more usages in PowerAuth projects.

Fix #212: Crypto 3.0: Remove deprecated methods

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/keyfactory/PowerAuthServerKeyFactory.java

This pull requests removes the `KeyDerivationUtil` class from powerauth-server and moves the commonly used logic in ECIES into `powerauth-crypto`.

Fix #224: Crypto 3.0: Move KeyDerivationUtil to powerauth-crypto

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/encryptor/ClientNonPersonalizedEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/NonPersonalizedEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/model/EncryptedMessage.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/model/NonPersonalizedEncryptedMessage.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/model/PersonalizedEncryptedMessage.java

I added warnings to the classes which will be deprecated once crypto version 2 is phased out.

Fix #191: Crypto 3.0: Deprecate legacy end-to-end encryption

---

docs/PowerAuth-2018.12.md
docs/Releases.md

I added the release page for release `2018.12`.

Fix #236: Documentation: Prepare release page for 2018.12

---

docs/Basic-definitions.md
docs/End-To-End-Encryption.md
docs/Standard-RESTful-API.md
powerauth-java-crypto/pom.xml
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesSharedInfo1.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/generator/IdentifierGenerator.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/model/Argon2Hash.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/model/RecoveryInfo.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/model/RecoverySeed.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/PasswordHash.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/activation/PowerAuthRecoveryCodeTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/Argon2Test.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/PasswordHashTest.java
powerauth-java-prov/src/main/java/io/getlime/security/powerauth/provider/CryptoProviderUtil.java
powerauth-java-prov/src/main/java/io/getlime/security/powerauth/provider/CryptoProviderUtilBouncyCastle.java
powerauth-java-prov/src/main/java/io/getlime/security/powerauth/provider/CryptoProviderUtilsSpongyCastle.java

The pull request contains following changes:
- Fix #250: Hashing function for storing PUK values in recovery codes
- Added `sharedInfo1` parameter for recovery code confirmation
- Recovery code generation and derivation
- Tests for password hashing and recovery code generation and derivation
- Added dependency on Bouncy Castle for Argon2 support
- Documentation updates

Crypto updates for recovery codes and PUKs

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/generator/IdentifierGenerator.java

Detection of duplicates is now done on `PUK`s, not on `pukDerivationIndex`es.

Fix #252: Detect duplicate PUKs when generating recovery codes

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/generator/KeyGenerator.java
powerauth-java-prov/src/main/java/io/getlime/security/powerauth/provider/CryptoProviderUtilBouncyCastle.java
powerauth-java-prov/src/main/java/io/getlime/security/powerauth/provider/CryptoProviderUtilsSpongyCastle.java

According to documentation the algorithm name in `SecretKeySpec` should not specify mode or padding.

Fix #272: Invalid algorithm specification during key conversion

---

pom.xml
powerauth-java-prov/src/main/java/io/getlime/security/powerauth/provider/CryptoProviderUtil.java

Note: Surprisingly, the "M1" dependency is correct here, see [plugin web](https://maven.apache.org/plugins/maven-deploy-plugin/download.cgi) for the details.
> **Apache Maven Deploy Plugin 3.0.0-M1**
> This is the current stable version of Apache Maven Deploy Plugin.

Fix #278: Update Maven plugins

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/enums/PowerAuthSignatureFormat.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/enums/PowerAuthSignatureTypes.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/signature/PowerAuthSignatureFormatTest.java
powerauth-java-http/src/main/java/io/getlime/security/powerauth/http/validator/ValueTypeValidator.java

This change also contains refactoring for `PowerAuthSignatureFormat.getFormatForSignatureVersion()` method and adds new functionality to that enumeration.

Fix #280: Signature format validator now supports Base64 signatures.

---

docs/PowerAuth-2019.05.md
docs/PowerAuth-2019.11.md

@hvge pls check the migration guides for the SDK and probably add some comment about the need for multiple 1.x versions for the SDK

Prepare release page for release 2019.11

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/keyfactory/PowerAuthClientKeyFactory.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/enums/PowerAuthSignatureTypes.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/keyfactory/PowerAuthServerKeyFactory.java

The pull request replaces the guessed signature type with `null` value to avoid unexpected behaviour (e.g. when there is a typo in signature type). See also: https://github.com/wultra/powerauth-restful-integration/pull/231

Fix #314: Improve logic for unknown signature type

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/KeyConvertor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/PublicKeyValidator.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/ec/InvalidPointTest.java

I added two public key validations:
- point at infinity not allowed as public key
- calculation of point order and its verification against order defined in EC curve

Fix #367: Perform full point validation during import

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesDecryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/model/Argon2Hash.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/HashBasedCounterUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/SideChannelUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/TokenUtils.java

Migration to BC library due to constant time array comparisons.

Fix #384: Use BC library for array comparison

---

docs/PowerAuth-2021.11.md
docs/PowerAuth-2022.04.md

Separation of releases `2021.11` and `2022.04` for better explanation of DB migration in mid-release.
See also:
https://github.com/wultra/powerauth-server/pull/683

Fix #398: Improve migration guide for release 1.2.5

---

powerauth-docs/test-vectors/signatures-offline.json
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/GenerateVectorDataTest.java

This PR fixes invalid test vectors in `signatures-offline.json`.

Fix #455: Correct test vectors for offline signatures

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/activation/PowerAuthClientActivation.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/vault/PowerAuthClientVault.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/EncryptorFactory.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesCryptogram.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/model/EciesParameters.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/EciesUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/activation/PowerAuthServerActivation.java

Fix #529: Fix typo in the error message

---

pom.xml
powerauth-docs/test-vectors/signatures-offline.json
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/signature/PowerAuthClientSignature.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/config/Base64SignatureConfiguration.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/config/DecimalSignatureConfiguration.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/config/SignatureConfiguration.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/HashBasedCounterUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/SignatureUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/TokenUtils.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/signature/PowerAuthServerSignature.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/GenerateVectorDataTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/signature/PowerAuthSignatureTest.java

(cherry picked from commit 6d81bf17f78b984388693a730e937933e7b2fd35)
Needs to be backported for backport of https://github.com/wultra/powerauth-server/pull/939

Fix #451: Allow overriding length of decimalized signatures (backport)

---

docs/Releases.md

(cherry picked from commit 6a87726525959c9673ddfaa7efe8f090ee78edfc)

Fix #578: Add 2023.12 and 2023.08 to releases (backport)

---

powerauth-java-crypto/pom.xml

- Make the scope `compile` instead of `provided`

Fix #605: Refactor BouncyCastle dependency

---

powerauth-java-crypto/pom.xml
powerauth-java-crypto/src/test/java/com/wultra/security/powerauth/crypto/lib/v4/jwt/TemporaryKeyTest.java

Test vectors for JWT requests and responses for algorithms `EC_384` and `EC_384_ML_L3`.

Fix #766: Generate test vectors for JWT used in temporary keys
