powerauth-java-cmd/src/main/java/io/getlime/security/client/app/Application.java

Added TrustManager that allows connection to servers with unsecured self-signed certificates

Added TrustManager 

---

pom.xml
powerauth-java-crypto/pom.xml
powerauth-java-http/pom.xml
powerauth-java-prov/pom.xml

Additional change: artifact powerauth-parent renamed to powerauth-crypto-parent.

Fix #159: JDK 9 support

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesDecryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesEnvelopeKey.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesFactory.java

See issue: https://github.com/wultra/powerauth-crypto/issues/207

Fix #207: Crypto 3.0: Create ECIES decryptor from envelope key and sharedInfo2

---

powerauth-docs/test-vectors/public-key-fingerprint-v2.json
powerauth-docs/test-vectors/public-key-fingerprint-v3.json
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/activation/PowerAuthClientActivation.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/model/ActivationVersion.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/ECPublicKeyFingerprint.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/activation/PowerAuthServerActivation.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/activation/PowerAuthActivationTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/GenerateVectorDataTest.java

This pull request introduces activation version 3 fingeprint calculation and updated tests + test vectors.

Fix #222: Crypto 3.0: Update fingerprint for activations

---

powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/activation/PowerAuthClientActivation.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/encryptor/ClientNonPersonalizedEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/client/vault/PowerAuthClientVault.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/NonPersonalizedEncryptor.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/ecies/EciesFactory.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/model/EncryptedMessage.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/model/NonPersonalizedEncryptedMessage.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/encryptor/model/PersonalizedEncryptedMessage.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/activation/PowerAuthServerActivation.java
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/server/vault/PowerAuthServerVault.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/activation/PowerAuthActivationTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/GenerateVectorDataTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/signature/PowerAuthSignatureTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/vault/VaultTest.java

Minor JavaDoc fixes, no code changes.

Fix #230: Fix JavaDoc warnings

---

pom.xml
powerauth-java-crypto/pom.xml
powerauth-java-http/pom.xml
powerauth-java-prov/pom.xml

Updated version to 0.22.0 and updated BC dependency.

Fix #243: Update version to 0.22.0

---

docs/PowerAuth-2019.05.md
docs/Releases.md

@hvge please check the comments related to mobile SDK, thanks.

Prepare release page for 2019.05 release

---

powerauth-java-crypto/pom.xml
powerauth-java-http/pom.xml
powerauth-java-prov/pom.xml

Upgrade of libraries to make sure there are no vulnerability warnings in the release.

Upgrade dependencies

---

pom.xml
powerauth-java-crypto/pom.xml
powerauth-java-http/pom.xml
powerauth-java-prov/pom.xml

Update of the version for `0.23.0` release.

Update version to 0.23.0 for release

---

docs/Basic-definitions.md
pom.xml
powerauth-java-crypto/pom.xml
powerauth-java-crypto/src/main/java/io/getlime/security/powerauth/crypto/lib/util/AESEncryptionUtils.java
powerauth-java-http/pom.xml
powerauth-java-prov/pom.xml

See: https://docs.oracle.com/javase/8/docs/api/javax/crypto/Cipher.html#getInstance-java.lang.String-

Fix #268: Rename padding parameter in AESEncryptionUtils

---

docs/PowerAuth-2019.05.md
docs/PowerAuth-2019.11.md
docs/PowerAuth-2020.05.md

Update of versions for last 2 releases and a new page for `2020.05`.

Fix #332: Prepare release page for 2020.05

---

powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/ec/InvalidPointTest.java

I added a test for point order validation simulating an EC curve fault attack by altering the curve order.

Add a test for invalid curve order simulating an EC curve fault attack

---

docs/PowerAuth-2021.05.md

I removed the Java EE projects for this release.

Fix #375: Prepare release page for 2021.05

---

pom.xml
powerauth-java-crypto/pom.xml
powerauth-java-http/pom.xml

A suggestion how to improve maven dependency management as a follow-up to https://github.com/wultra/powerauth-crypto/pull/401

Improve maven dependency management

---

.github/workflows/maven-deploy.yml
.github/workflows/maven-test.yml

propagate secrets for maven test

---

powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/activation/PowerAuthRecoveryCodeTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/encryption/EciesEncryptorTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/generator/ActivationCodeGeneratorTest.java
powerauth-java-crypto/src/test/java/io/getlime/security/powerauth/crypto/lib/util/KeyConversionUtilsTest.java
powerauth-java-http/src/main/java/io/getlime/security/powerauth/http/PowerAuthRequestCanonizationUtils.java

- Use URLEncoder.encode(String, StandardCharset)
- Add final modifier

Fix #478: Review Java warnings

---

.github/workflows/codeql-analysis.yml

Fix #499: Add CodeQL Analysis

---

docs/Activation-via-Activation-Code.md
docs/MAC-Token-Based-Authentication.md

- Fixed `H_K_DEVICE_PUBLIC` calculation (unwanted key conversion)
- Use new basic definitions in pseudo code

Quick documentation fix

---

.github/workflows/maven-deploy.yml

(cherry picked from commit 970009d869ea78d52d4900f7f67f605953fbbcb6)

Fix: #555: Signing by GPG for Maven release (backport)

---

docs/PowerAuth-2023.12.md

Fix #564: Create PowerAuth-2023.12.md
(cherry picked from commit 018487921bf55d32f0302374ed8f95c6479f21fe)

Fix #564: Create PowerAuth-2023.12.md (backport)

---

docs/Activation-Code.md
docs/Activation-via-Activation-Code.md
docs/Activation-via-Custom-Credentials.md
docs/Activation-via-Recovery-Code.md
docs/Activation.md
docs/Advanced-Activation-Flows.md

Fix invalid links in the documentation

---

docs/Releases.md

Link PowerAuth-2024.10 page

---

docs/Releases.md

A follow-up to #651
(cherry picked from commit 91be36e117c360df6b72e225cb206c0977c205ae)

Link PowerAuth-2024.10 page (backport)

---

powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/authentication/PowerAuthClientAuthentication.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/keyfactory/PowerAuthClientKeyFactory.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/v4/activation/PowerAuthClientActivation.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/v4/authentication/PowerAuthClientAuthentication.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/v4/keyfactory/PowerAuthClientKeyFactory.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/v4/token/ClientTokenGenerator.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/v4/vault/PowerAuthClientVault.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/client/vault/PowerAuthClientVault.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/AuthenticationCodeLegacyUtils.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/util/ECPublicKeyFingerprint.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/lib/v4/PqcDsa.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/activation/PowerAuthServerActivation.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/authentication/PowerAuthServerAuthentication.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/keyfactory/PowerAuthServerKeyFactory.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/token/ServerTokenVerifier.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/activation/PowerAuthServerActivation.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/authentication/PowerAuthServerAuthentication.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/keyfactory/PowerAuthServerKeyFactory.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/token/ServerTokenGenerator.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/token/ServerTokenVerifier.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/util/DataDigest.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/v4/vault/PowerAuthServerVault.java
powerauth-java-crypto/src/main/java/com/wultra/security/powerauth/crypto/server/vault/PowerAuthServerVault.java
powerauth-java-crypto/src/test/java/com/wultra/security/powerauth/crypto/activation/ActivationStatusBlobInfoTest.java
powerauth-java-crypto/src/test/java/com/wultra/security/powerauth/crypto/authentication/PowerAuthAuthenticationCodeTest.java
powerauth-java-crypto/src/test/java/com/wultra/security/powerauth/crypto/lib/util/GenerateVectorDataTest.java
powerauth-java-crypto/src/test/java/com/wultra/security/powerauth/crypto/lib/v4/PqcDsaTest.java

This pull requests separates v3 and v4 classes for client and server usage and cleans up the API to be used from client and server.

Fix #756: Separate v4 server and client classes
